### ISSUE TITLE
access_type='offline' and refresh token

### ISSUE THREAD

**Issue by NotSqrt** [klen/aioauth-client#111]
Hi,

With the `GoogleClient`, we can specify `access_type='offline'`, but how does that relate to using the refresh token automatically, to avoid an explicit redirection after the 3600 seconds of TTL of the token ?

https://developers.google.com/identity/protocols/OAuth2WebServer#offline

Thanks !

**Comment by klen** [comment]
```python
client = GoogleClient(client_id, client_secret)
```

Authorize user
```python
redirect_url = client.get_authorize_url(access_type='offline', prompt='consent', scope='...')
# redirect a user to the url somehow
```

Process Google Callback
```python
code = request.query.get('code')
token, meta = client.get_access_token(code)
refresh_token = meta.get('refresh_token')
# Save the refresh token for later use
```

Later: use the refresh token to get an actual access token:
```python
new_access_token, meta = client.get_access_token(refresh_token, grant_type='refresh_token')
# Use the new access token for API requests.
```
