### ISSUE TITLE
don't raise HTTPBadRequest every time

### ISSUE THREAD

**Issue by nnnewb** [klen/aioauth-client#132]
https://github.com/klen/aioauth-client/blob/54f58249496c26965adb4f752f2b24cfe18d0084/aioauth_client.py#L148-L150

it's confusing, the `reason` say "HTTP status code: 403" but the attribute `status_code` and `status` are both 400.

`response.raise_for_status` should be better.

**Comment by syrkit** [comment]
Agreed.

FWIW, these exceptions are meant to be used on the server side, not client side.

**Comment by klen** [comment]
Fixed in 0.18.0
