### ISSUE TITLE
request always get empty dict

### ISSUE THREAD

**Issue by nnnewb** [klen/aioauth-client#133]
https://github.com/klen/aioauth-client/blob/54f58249496c26965adb4f752f2b24cfe18d0084/aioauth_client.py#L154-L156

I'm trying to use `OAuth2Client.request` get some resource from own server, but `client.request` always return empty dict. I found out the problem happens in `Client._request`.

maybe you can add a parameter like `raw_content`, let us control how to deal with the response?

**Comment by klen** [comment]
Fixed in 0.18.0
