### ISSUE TITLE
GitHub example in README.rst seems broken

### ISSUE THREAD

**Issue by TrueBrain** [klen/aioauth-client#166]
First off, thank you for this library. But, I have a question :)

When executing the code in:

https://github.com/klen/aioauth-client/blob/develop/README.rst#usage

There seems to be an issue:

```python
user_info = yield from response.json()
```
The `response` object is a dict, not the `response` object: https://github.com/klen/aioauth-client/blob/develop/aioauth_client.py#L147

A simple fix is by doing this, of course:

```python
    response = await github.request('GET', 'user')
    print(response)
```

Similar issue seems to be in the example:
https://github.com/klen/aioauth-client/blob/develop/example/app.py#L98

There it reads:

```python
    response = yield from github.request('GET', 'user')
    body = yield from response.read()
```

Which too fails, because `response` is a dict.

Of course these are all easy to fix, but I was mostly wondering if it was intended, as I too expected the response object as return value. Mainly, as that allows for checking the `status` field in the request, to see if the request went through okay. It would also give access to GitHub headers indicating the rate limiter current status, etc. Of course with the access_token it is easily enough to make that request directly via aiohttp myself, but it just made me wonder why this decision?

Thank you again for the library, saved me a bit of time :)

**Comment by klen** [comment]
Thank you, fixed.
