### ISSUE TITLE
Undeclared dependency on `yarl` package

### ISSUE THREAD

**Issue by twelvelabs** [klen/aioauth-client#187]
Attempting to import `aioauth-client` raises:

```
ModuleNotFoundError: No module named 'yarl'
```

Looks like it needs to be added here:

https://github.com/klen/aioauth-client/blob/18a862730395f279d01f94409474cf602337ef2f/setup.cfg#L32

**Comment by klen** [comment]
@twelvelabs Thank you for the report!
