### ISSUE TITLE
Vkontakte

### ISSUE THREAD

**Issue by iho** [klen/aioauth-client#3]
Hello. 
How about this popular socila network?

**Comment by klen** [comment]
Hello,

You always can use any OAuth1/2 provider like this:

```python

vk = OAuth2Client(
    authorize_url='http://api.vkontakte.ru/oauth/authorize',
    access_token_url='https://api.vkontakte.ru/oauth/access_token')

# ...
authorize_url = yield from vk.get_authorize_url()
# ...

```
But I've added VK class to the library. Please enjoy and don't be hesitate to report me if there any problems with. Because I didn't test it.
