### ISSUE TITLE
Injecting own aiohttp.ClientSession instance explicitly

### ISSUE THREAD

**Issue by yeahframeoff** [klen/aioauth-client#62]
For now, all requests in OAuth Clients in this package are performed using `aiohttp.request` function. But there are cases, when I need to use my own ClientSession instance instead of leaving it up to oauth lib - that is useful for both testing and ease of configuration.

So, I imagine it like this:

```python
from aioauth_client import OAuth2Client

from aiohttp import ClientSession

custom_session = ClientSession(custom_setting='custom_value')

client = OAuth2Client(session=custom_session)
```

One possible case, why users would need it is a client session instance bound to a fake server emulating an API (like here https://github.com/aio-libs/aiohttp/blob/master/examples/fake_server.py#L144), which makes testing some service relying on external API isolated from the actual API easy and honest.

**Comment by ElSaico** [comment]
Another use case is when you want to extend a framework (in my case,  https://github.com/rougeth/bottery) which already provides a `ClientSession` to its modules.
