### ISSUE TITLE
In example app Facebook auth not working

### ISSUE THREAD

**Issue by radiophysicist** [klen/aioauth-client#78]
When trying to use FB auth in example app Facebook shows 'App Not Setup' error 
(similar to the shown here: https://i.stack.imgur.com/p2Zsn.png)

**Comment by cpwr** [comment]
@radiophysicist https://www.hull.io/help/facebook-app-not-setup-error/
I believe this could help you.

**Comment by radiophysicist** [comment]
I've meant that something like this should probably be done for example app included with the library. Other services (at least github and google) are working out of the box

**Comment by cpwr** [comment]
@radiophysicist why do you think this is incorrect?
In my opinion - **maybe** there should be a little hint in library documentation, but the thing you are asking for is not about OAuth (and this library) **at all**. You can still write to Facebook to resolve this issue.

**Comment by radiophysicist** [comment]
The example app https://github.com/klen/aioauth-client/blob/develop/example/app.py contains working examples of OAuth for several services. The app is already registered (probably by the library author) in them using URL fuf.me (pointing to 127.0.0.1).
I tried github, google and facebook auth. The latter is not working with the error mentioned in my initial message. It seems that something should be done with example app registration on facebook using URL fuf.me (and obviously it could be done only by person registered the app on facebook initially)

**Comment by cpwr** [comment]
@radiophysicist ok, where the fuf.me:5000 was metioned as an example app in your initial message?
FYI, URL fuf.me is not pointing to 127.0.0.1. It is two different apps
